urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'http://localhost:3000'
api:
  auth: true
features:
  publicApi:
    enabled: true
    port: 3000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - 'https://inscriptions-dapp.vercel.app'
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
